name: mvp-web-client-ci.yml

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    if: github.ref_name == 'master'
    name: "Test site using Playwright"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name: Install dependencies
        run: |
          cd tests
          npm ci
          npx playwright install-deps
          npx playwright install

      - name: Run Playwright Tests
        continue-on-error: false
        run: |
          npx playwright test e2e --reporter=html --config playwright.config.ts

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/release/${{ steps.package-version.outputs.current-version}}',
              sha: context.sha
            })
