name: production.yml

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  production:
    name: Deploy to Cloudflare Pages (Production)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Deploy
        uses: ./.github/workflows/deploy-to-pages.yml

      - name: Get NPM version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/release/${{ steps.package-version.outputs.current-version}}',
              sha: context.sha
            })
